### ISSUE TITLE
video not found

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#19]
video files listed in project file under animal ID, but when try to play in GUI, states no file found for time

**Comment by mfpleite** [comment]
I think I experienced this when testing in Windows... I'll have to look at this at a later point when fixing bugs in my windows environment.

**Comment by mfpleite** [comment]
Ok I think I sorted this out alongside codec problems in Windows. Can you close the issue once you confirm it is working for you?

**Comment by mikailweston** [comment]
not working. finds file but error message: 

> Changing video file:  F:\epilepsy files\video\97\20210310131029.mp4
Updated FFT
Window changesd to: [1615386132.2011466, 1615386149.9446943]
Video - Error: Failed to load source.

**Comment by mikailweston** [comment]
Actually, my video folder was pointing to the wrong directory.

If the video is not found error message as above, but if project file is updated ( by setting video folder correctly), need to restart PyEcog to get any videos to play

**Comment by mikailweston** [comment]
Approximately 1 hour difference between video file and datetime on EEG:

- Multiple date times doing different things as in screen shot below
- Video playing cursor jumps when video starts to a different place


![image](https://user-images.githubusercontent.com/7851321/112311086-357bec00-8c9d-11eb-8971-81b79f8e1a91.png)

**Comment by mikailweston** [comment]
also manual time adjustment would be helpful

**Comment by mfpleite** [comment]
Videos should now be behaving a bit better. The only known issue that I couldn't solve for now is that when switching to some video files the video surface starts playing on the background, even if I send a pause command after loading. Worst of all it doesn't even send position change signals, I think this is probably some bug deeper in the Qt media API, I couldn't find a workaround for now, anyway I think it is not too annoying for the user

**Comment by mfpleite** [comment]
manual time shift for videos still in the request list

**Comment by mfpleite** [comment]
done
