### ISSUE TITLE
Very slow loading neuropixel binary data

### ISSUE THREAD

**Issue by mikailweston** [KullmannLab/pyecog2#32]
## Error with concurrent plotting of data that overlaps in time

By default all NP data is acquired at the same time: multiple LF and AP files per folder, 1 each for each probe.

If there is more than one file in the folder PyEcog plots all data from the same folder concurrently even if only one file is selected in the file tree
![image](https://user-images.githubusercontent.com/7851321/124097512-88f79600-da53-11eb-89b5-90c233e75751.png)
![image](https://user-images.githubusercontent.com/7851321/124093579-e5f14d00-da4f-11eb-887c-1ec023923e30.png)

300s to display 30s of 385 channel data from 4 files (2 x LF and 2 x AP)

_Work around: put each file in a separate folder_ 
![image](https://user-images.githubusercontent.com/7851321/124095681-d1ae4f80-da51-11eb-88a0-191243e26eb5.png)
![image](https://user-images.githubusercontent.com/7851321/124095745-e12d9880-da51-11eb-9423-fe2f3c4a4b08.png)

## Data loading still slow

  - LF data: 25s for 385 channels (sample rate ~2500 Hz)
  -  AP data: 120s for 385 channels (sample rat ~30,000 Hz)

*@mfpleite  Would it be possible to plot down sampled array as a whole rather than each channel individually?*

**Comment by mfpleite** [comment]
> @mfpleite Would it be possible to plot down sampled array as a whole rather than each channel individually?
I don't understand what you mean

Regarding multiple concurrent files: that is the original intended behavior to cope with chopped telemetry data. We didn't expect multiple files of the same sort overlapping (on purpose) in time. We can think about implementing this, but it would be a new feature.

To speed up the plots we can impose a maximum data size to be displayed at the start - any suggestions on what this size might be?

**Comment by mfpleite** [comment]
when opening a folder we can make each file a different animal in the temporary project if that helps...

**Comment by mfpleite** [comment]
> when opening a folder we can make each file a different animal in the temporary project if that helps...
I have made this change in the last comit

**Comment by mikailweston** [comment]
Thanks. I have shared a 27GB AP file and 2GB corresponding LF file. 

I think the main issue with the speed of display is computing the scale for each channel in the overview, and then drawing each pen + doing the same for inset view. 

It would be helpful to limit the amount of data viewed in the overview plot for NP data, for example a few minutes. 

Would a way of speeding this up be to compute a downsampled and scaled numpy array and saving this in a buffer before drawing the overiew pens. The insetview could be limited to 30s of data that hasn't been downsampled?

**Comment by mikailweston** [comment]
Also would it help to turn off autorange in the view box until after plotting?

https://stackoverflow.com/questions/17103698/plotting-large-arrays-in-pyqtgraph/17108463

**Comment by mfpleite** [comment]
> Also would it help to turn off autorange in the view box until after plotting?

It is already disabled in lines 113 and 114 of paired_graphics_view.py.
The thread might have good tips, I'll have a look.

**Comment by mfpleite** [comment]
Ok the decimation closes this for the time being :)
